### ISSUE TITLE
min default dot size when changing the circle radius

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/epwmap#20]
Hi Mostapha, thanks for adding this new function. but it seems there is a displaying issue about min default dot size. is that possible to do the "relative" size for each dot that is within the viewport?

![image](https://cloud.githubusercontent.com/assets/9031066/25592480/f558a820-2e86-11e7-890c-9eeb8fa68b55.png)

**Comment by mostaphaRoudsari** [comment]
Hi @MingboPeng, Thanks. That should be possible but at the same time can be misleading. With the current set-up it shows that SF doesn't have much strong heat stress however with resizing one can check a zoomed graph and make a wrong conclusion.

We can 1. Add control for min / max circle size and 2. use colors instead of size to map the values. I leave this issue open so we can address it in the next round of development.

**Comment by mostaphaRoudsari** [comment]
This is removed now from the interface. We can add it back later if really needed. Let's keep the map light and add the extra data visualization in a new page.
